### ISSUE TITLE
Footer is not dynamic

### ISSUE THREAD

**Issue by mutludev** [ieeegesb/ieeetanitimsitesi#7]
a tags in `Footer.js` must be dynamically generated from `committees.json` file

**Comment by GiorgosDrivas** [comment]
Hello! If I understand correct, you would like to dynamically generate the a tags inside the committees div of the footer from the committees.json file and more specifically the 'shortname' and the name as the href attribute. 

I am interested in resolving this issue, should it be permissible.

**Comment by mutludev** [comment]
Hi George, yes, you understood it correctly. I noticed that you've made changes and merged them into your fork. If you could create a pull request for this repository, I can merge it. Thanks!

**Comment by mutludev** [comment]
Merged. You can check the other issues if you want, @GiorgosDrivas; they're kind of the same thing.

Closing issue.
